[package]
name = "novella"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
num = "0.4.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
