[package]
name = "nvcore"
version = "0.0.0"
description = "Novella core"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
test = true
[dependencies]
bitvec = "0.22.3"
num = "0.4.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
nvproc = { path = "../procmacros" }
getset = "0.1.2"
utils = { version = "0.1.0", path = "../utils" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
bevy_ecs = "0.6.1"
dyn-clone = "1.0.4"
anyhow = "1.0.54"
