[package]
name = "nvcore"
version = "0.0.0"
description = "Novella core"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
test = true
[dependencies]
bitvec = "0.22.3"
num = "0.4.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
