/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace nv {

template<typename T = void>
struct Box;

struct EventQueue;

template<typename T = void>
struct VecDeque;

struct Action {
  void (*_0)(Mir*);
};

struct Mir {
  Box<EntityManager> em;
  Box<Project> proj;
  Box<EventQueue> event_queue;
  Box<VecDeque<Action>> action_queue;
};

extern "C" {

Mir create();

void say_hello(const Mir *self);

} // extern "C"

} // namespace nv
