extern crate cbindgen;

use std::{env, path::PathBuf};

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let mut c_api_path = PathBuf::from(crate_dir.clone());
    c_api_path.push("../c_api");
    c_api_path.push("include");
    c_api_path.push("nv_api");
    c_api_path.set_file_name("nv_api_internal.h");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_autogen_warning(r"//Autogenerated by cbindgen-rust-wrapper. Do not modify")
        .with_namespace("nv_internal")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(c_api_path);
}
