//Autogenerated by cbindgen-rust-wrapper. Do not modify

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace nv_internal {

extern "C" {

Mir *create_mir();

/// # Safety
/// There should be no other references to the mir at this point!
void free_mir(Mir *mir);

} // extern "C"

} // namespace nv_internal
