//Autogenerated by cbindgen-rust-wrapper. Do not modify

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace nv_internal {

} // namespace nv_internal
