// Autogenerated by cbindgen-rust-wrapper. Do not modify

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>
#include <ostream>

namespace nv_internal {

struct Context {
  Mir *mir;
};

extern "C" {

Context create();

void destroy(Context *ctx);

}  // extern "C"

}  // namespace nv_internal
