// Autogenerated by cbindgen-rust-wrapper. Do not modify

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>
#include <ostream>

struct Mir;

struct Context {
  Mir *mir;
};

extern "C" {

Context create();

void destroy(Context *ctx);

void say_hello(const Context *self);

}  // extern "C"
